spring.application.name=Donation

spring.datasource.url=jdbc:mysql://localhost:3307/BloodDonation
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


//Mail

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=legendbladeno1@gmail.com
spring.mail.password=xkecxtlqkxmilmwn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

//Jwt
jwt.secret=mySecretKey123456789012345678901234567890
jwt.expiration=86400000
